__author__ = 'dhanannjay.deo'

rename_map = {
    'ANAKAPALLE': 'ANAKAPALLI',
    'ANANTPUR': 'ANANTAPUR',
    'ARAKU': 'ARUKU',
    'AUTONOMOUS DISTRICT': 'AUTONOMOUS DISTS',
    'BAHARAMPUR': 'BERHAMPORE',
    'BARABANKI': 'BARA BANKI',
    'BARDHAMAN DURGAPUR': 'BURDWAN',
    'BATHINDA': 'BHATINDA',
    'BHANDARA-GONDIYA': 'BHANDARA - GONDIYA',
    'BISHNUPUR': 'VISHNUPUR',
    'CHEVELA': 'CHELVELLA',
    'CHIKKBALLAPUR': 'CHIKBALLAPUR',
    'CHITTOR': 'CHITTOOR',
    'FEROZPUR': 'FEROZEPUR',
    'HISAR': 'HISSAR',
    'JAHANJHARPUR': 'JHANJHARPUR',
    'JANJGIR-CHAMPA': 'JANJGIR',
    'JHALAWAR-BARAN': 'JHALAWAR',
    'KHEDA': 'KHED',
    'MAHBUBNAGAR':'MAHABUBNAGAR',
    'MALDAHA DAKSHIN': 'MALDA',
    'MANDSOUR': 'MANDSAUR',
    'MAVELIKKARA': 'MAVELIKARA',
    'MEDINIPUR': 'MIDNAPORE',
    'MEHSANA': 'MAHESANA',
    'NAINITAL-UDHAMSINGH NAGAR': 'NAINITAL',
    'NARSAPURAM': 'NARASAPUR',
    'PALAMAU': 'PALAMU',
    'PEDDAPALLE': 'PEDDAPALLI',
    'PURNIA': 'PURNEA',
    'RATNAGIRI-SINDHUDURG':'RATNAGIRI',
    'SECUNDARABAD': 'SECUNDERABAD',
    'SONIPAT': 'SONEPAT',
    'SURGUJA': 'SARGUJA',
    'TONK-SAWAI MADHOPUR': 'TONK'
    }

missing_geometry = ['A&N ISLANDS', 'DADRA & NAGAR HAVELI', 'DAMAN & DIU', 'BIRBHUM', 'LAKSHADWEEP', 'PUDUCHERRY']
missing_data = ['NA']